using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace Web_TPMTrakDashboard.GenericAndon.Model
{
    public class DTO
    {
    }
    public class CockpitData
    {
        public string MachineId { get; set; }
        public string MachineStatus { get; set; }
        public string MachineRemarks { get; set; }
        public string MachineOEE { get; set; }
        public string SmileyImagePath { get; set; }
        public string StatusImage { get; set; }
        public string GroupName { get; set; }
        public string BackColor { get; set; }
        public string PlantID { get; set; }
        public string ShowSmileyBlock { get; set; }
        public string SmileySize { get; set; }
        public string BorderClass { get; set; }
        public string MachineFontSize { get; set; }
        public string ProductionMachineNameFontSize { get; set; }
        public string CockpitBoxWidth { get; set; }
        public string LeftMargin { get; set; } = "10";
        public string TopMargin { get; set; } = "20";

        public string TableLayout { get; set; } = "auto";


        public List<CockpitUserControlData> Values { get; set; }

        public CockpitData()
        {
            Values = new List<CockpitUserControlData>();
        }
    }
    public class CockpitUserControlData
    {
        public string Tag { get; set; }
        public string LabelText { get; set; }
        public string LabelValue1 { get; set; }
        public string LabelValue2 { get; set; }
        public string ColorProperties { get; set; }
        public string ForeColor { get; set; }
        public string ForeColorTitle { get; set; }
        public string BackColor { get; set; }
        public string BackColorTitle { get; set; }
        public string FontSizeInnerData { get; set; }
        public string HyperLink { get; set; }
        public string MachineName { get; set; }
        public string TextAlign { get; set; }
        public string DataFontSize { get; set; }
        public string CellID { get; set; }

    }
    public class AndonSettingEntity
    {
        public string ShowSmileyBlock { get; set; }
        public string SmileySize { get; set; }
        public string SortOrder { get; set; }
        public string OrderBy { get; set; }
        public string AndonTitle { get; set; }
        public string PlantToDisplay { get; set; }
        public int ScreenFlipInterval { get; set; }
        public string ShowFooterBlock { get; set; }
        public string ShowMsgBox { get; set; }
        public int DataRefreshInterval { get; set; }
        public string DateFormatForHeader { get; set; }
        public string TimeFormatForHeader { get; set; }
        public string ScrollingText { get; set; }
        public bool ShowCurvedBox { get; set; }
        public string FormFontSize { get; set; }
        public bool EnableImage { get; set; }
        public bool EnableVideo { get; set; }
        public int EnableSlideShowAfterNSecInterval { get; set; }
        public string ImagePath { get; set; }
        public string VideoPath { get; set; }
        public string FontFamily { get; set; }
        public string FontStyle { get; set; }
        public string BorderClass { get; set; }
        public int ScheduleInterval { get; set; }
        public string PoojaViewType { get; set; }
    }
    public class AndonDefaultsEntity
    {
        public string Parameter { get; set; }
        public string ValueInText { get; set; }
        public string ValueInText2 { get; set; }
        public int ValueInInt { get; set; }
        public bool ValueInBool { get; set; }
        public string TextAlign { get; set; }
        public string DataFontSize { get; set; }
        public string LabelFontSize { get; set; }
        public string CellID { get; set; }

    }
    public class AllAdnonEntity
    {
        public string AutoGeneratedID { get; set; }
        //public string PlantID { get; set; }
        // public string CellID { get; set; }
        // public string Frequency { get; set; }
        public List<CockpitData> CockpitData { get; set; }
        public AndonSettingEntity AdnonSetting { get; set; }
        public List<ScheduleKTAEntity> ScheduleKTAData { get; set; }
        //public List<PoojaCastingMeltingEntity> PoojaCastingData { get; set; }
        public DataTable PoojaCastingData { get; set; }
        public DataTable PoojaCastingColors { get; set; }
    }
    public class AllAdnonStoreEntity
    {
        public string AutoGeneratedID { get; set; }
        public List<StoreAndonKTAEntity> StoreData { get; set; }
        public SettingsViewEntityStore AdnonSetting { get; set; }
    }
    public class StoreAndonKTAEntity
    {
        public string PlantID { get; set; }
        public string CellID { get; set; }
        public string Machine { get; set; }
        public string Component { get; set; }
        public string LabelScrolling { get; set; }
        public string Operation { get; set; }
        public string OpDesc { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string MachineFontSize { get; set; }
        public List<StoreAndonKTAEntity> ComponentList { get; set; }
        public string FontSizeInnerData { get; set; }
        public string FontSizeHeaderData { get; set; }
        public bool LabelVisible { get; set; }
        public bool LinkVisible { get; set; }
    }
    public class EffyColorEntity
    {
        public string GoodColor { get; set; }
        public string ModerateColor { get; set; }
        public string BadColor { get; set; }

    }
    public class ScreenEntity
    {
        public string Screen { get; set; }
        public int Order { get; set; }
    }

    //public class AndonSettingEntity
    //{
    //    public string Column { get; set; }
    //    public string CustomColumnName { get; set; }
    //    public string SortOrder { get; set; }
    //    public bool Visibility { get; set; }
    //    public string TextAlign { get; set; }
    //    public string LabelFontSize { get; set; }
    //    public string DataFontSize { get; set; }

    //}
    public class SettingsViewEntity
    {
        public string AndonTitle { get; set; }
        public string PlantToDisplay { get; set; }
        public string DataDisplayInterval { get; set; }
        public string ScreenFlipInterval { get; set; }
        public int ShowSmileyBlock { get; set; }
        public int MsgBlockEnabled { get; set; }
        public int ShowFooterBlock { get; set; }
        public string FontFamily { get; set; }
        public string FontStyle { get; set; }
        public string ShowSmileyBlockSize { get; set; }
        public string FormFontSize { get; set; }
        public string ImageFilePath { get; set; }
        public int EnableImage { get; set; }
        public int EnableVideo { get; set; }
        public string VideoFilePath { get; set; }
        public string ImageFlipInterval { get; set; }
        public int ShowCurvedBoxes { get; set; }
        public string DateFormat { get; set; }
        public string TimeFormat { get; set; }
        public string PrimaryScreen { get; set; }
        public string OrderBy { get; set; }
        public string ScrollingText { get; set; }
        public string ScheduleKTAFlipInterval { get; set; }
        public string PoojaViewType { get; set; }
        public string KTAHeaderFontSize { get; set; }
        public string KTAContentFontSize { get; set; }
        public string KTAWrapContent { get; set; }
    }
    public class ScheduleKTAEntity
    {
        public string PlantID { get; set; }
        public string CellID { get; set; }
        public string MachineID { get; set; }
        public string BackColor { get; set; }
        public string ComponentID { get; set; }
        public string ScheduleDate { get; set; }
        public string ComponentStatus { get; set; } = "";
        public List<ScheduleKTAEntity> ComponentList { get; set; }
        public string FontSizeInnerData { get; set; }
        public string DataFontSize { get; set; }
        public string MachineNameFontSize { get; set; }
        public string LabelScrolling { get; set; }
        public string KTAWrapContent { get; set; }

    }

    public class AndonDefaultsEntityStore
    {
        public string Parameter { get; set; }
        public string ValueInText { get; set; }
        public string ValueInText2 { get; set; }
        public int ValueInInt { get; set; }
        public bool ValueInBool { get; set; }
        public string TextAlign { get; set; }
        public string DataFontSize { get; set; }
        public string LabelFontSize { get; set; }
        public string CellID { get; set; }
    }
    
    public class SettingsViewEntityStore
    {
        public string AndonTitle { get; set; }
        public string PlantToDisplay { get; set; }
        public int DataDisplayInterval { get; set; }
        public int ScreenFlipInterval { get; set; }
        public int ShowSmileyBlock { get; set; }
        public int MsgBlockEnabled { get; set; }
        public int ShowFooterBlock { get; set; }
        public string FontFamily { get; set; }
        public string FontStyle { get; set; }
        public string ShowSmileyBlockSize { get; set; }
        public string MachineFontSize { get; set; }
        public string ImageFilePath { get; set; }
        public int EnableImage { get; set; }
        public int EnableVideo { get; set; }
        public string VideoFilePath { get; set; }
        public string ImageFlipInterval { get; set; }
        public int ShowCurvedBoxes { get; set; }
        public string DateFormat { get; set; }
        public string TimeFormat { get; set; }
        public string PrimaryScreen { get; set; }
        public string OrderBy { get; set; }
        public string ScrollingText { get; set; }
        public string ScheduleKTAFlipInterval { get; set; }
        public string PoojaViewType { get; set; }
        public string KTAHeaderFontSize { get; set; }
        public string KTAContentFontSize { get; set; }
    }
    public class PoojaCastingParameterList
    {
        public string ParameterText { get; set; } = string.Empty;
        public string ParameterValue { get; set; } = string.Empty;
        public string backColor { get; set; } = string.Empty;
        public string Display1 { get; set; } = string.Empty;
        public string Display2 { get; set; } = string.Empty;
        //public class ICockpitStyle
        //{
        //    public string GoodRunning { get; set; }
        //    public string BadlyRunning { get; set; }
        //    public string ModeratelyRunning { get; set; }
        //}

    }
    public class PoojaCastingFurnaceEntity
    {
        public string Furnace { get; set; } = string.Empty;
        public string HeatCode { get; set; } = string.Empty;
        public string HeatNo { get; set; } = string.Empty;
        public string GradeID { get; set; } = string.Empty;
        public string GradeNorm { get; set; } = string.Empty;
        public int Settings { get; set; } = 0;
        public DateTime Date { get; set; } = DateTime.Now;
        public DataTable dtParameters { get; set; } = new DataTable();
        public string ParameterText { get; set; } = string.Empty;
        public string ParameterValue { get; set; } = string.Empty;
    }
    public class PoojaCastingMeltingEntity
    {
        public string Furnace { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public List<PoojaCastingParameterList> ParameterList { get; set; } = new List<PoojaCastingParameterList>();
    }

    public class AndonSettingsEntity
    {
        public string ColumnName { get; set; } = string.Empty;
        public string DisplayText { get; set; } = string.Empty;
        public string SortOrder { get; set; } = string.Empty;
        public int Visibility { get; set; } = 0;
        public string TextAlign { get; set; } = string.Empty;
        public string LabelFontSize { get; set; } = string.Empty;
        public string DataFontSize { get; set; } = string.Empty;
        public string CellID { get; set; } = string.Empty;
    }
    public class AndonProductionEntity
    {
        public string AutoGenerateID { get; set; } = string.Empty;
        //public List<AndonEntity> ProductionData { get; set; }
        public DataTable ProductionData { get; set; }
        public List<AndonSettingsEntity> HeaderData { get; set; } = new List<AndonSettingsEntity>();
        public AndonSettingEntity AndonSettings { get; set; }
    }

}